/**
 * kassette is a development server, used mainly for testing, which proxies requests and is able to easily manage local mocks.
 *
 * @packageDocumentation
 */

export {
  APIOptions,
  BaseSpec,
  Body,
  BodySpec,
  ChecksumArgs,
  CLIConfigurationSpec,
  CLIOptions, // internal
  ConfigurationPropertySource,
  ConfigurationSpec,
  Connection,
  ConsoleSpec,
  Delay,
  FilterSpec,
  Headers,
  HeadersSpec,
  HookAPI,
  HookFunction,
  HostnameSpec,
  IBaseRequest,
  IConfigurationProperty,
  IFetchedRequest,
  IMergedConfiguration,
  IMock,
  Include,
  IProxyConnectAPI,
  IResponse,
  ListMode,
  ListOrFilter,
  ListSpec,
  LocalPayload,
  MapSpec,
  MaybeAsync,
  MethodSpec,
  MockBody,
  MockData,
  MockingOptions,
  Mode,
  OnExitFunction,
  OnListenFunction,
  OnListenProps,
  OnProxyConnectFunction,
  PathnameSpec,
  Payload,
  PayloadOrigin,
  PayloadWithOrigin,
  PortSpec,
  ProtocolSpec,
  ProxyConnectMode,
  QuerySpec,
  RawBody,
  RemotePayload,
  RequestPayload,
  ResponseStatus,
  runFromAPI,
  runFromCLI, // internal
  RunResult,
  Spec,
  Status,
  UserPayload,
} from './app';
export { JSONData } from './lib/json';
export { NonSanitizedArray, RecursiveArray } from './lib/array';
