name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Tests

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # current LTS
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install playwright
        run: npx playwright install --with-deps

      - name: Run lint
        run: npm run lint

      - name: Run format:check
        run: npm run format:check

      - name: Run unit tests
        run: npm run ut:coverage

      - name: Run end to end tests
        run: npm run e2e:coverage

      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 #v4.5.0
        with:
          file: ./coverage/lcov.info
          flags: ut
          disable_search: true
          use_oidc: true

      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 #v4.5.0
        with:
          file: ./coverage-e2e/lcov.info
          flags: e2e
          disable_search: true
          use_oidc: true

      - name: Build API documentation
        run: npm run apidoc
