name: Continuous Integration

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  tests:
    name: Tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 12.x # current LTS

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format:check
        run: npm run format:check

      - name: Run unit tests
        run: npm run ut

      - name: Run end to end tests
        run: npm run e2e
