name: update

on:
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npx npm-check-updates -u
      - run: npm install --ignore-scripts
      - run: npm update --ignore-scripts
      - name: Create pull request
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7.0.1
        with:
          commit-message: 'chore(deps): update all dependencies'
          branch: dependencies
          title: Update all dependencies
          body: Update all dependencies
